name: Deploy Pages

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build generateHTML --parallel
    - name: Deploy Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        branch: gh-pages
        folder: build/docs
